# Generated by Django 2.2.13 on 2020-06-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceuser',
            name='is_retailer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='flZdKIl7Nb1O7kxj', unique=True),
        ),
    ]
