# Generated by Django 2.2.13 on 2020-06-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_retailer',
        ),
    ]
