# Generated by Django 2.2.13 on 2020-06-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('new', 'new'), ('best rated', 'best rated'), ('best seller', 'best seller')], max_length=1),
        ),
    ]
