# Generated by Django 2.2.13 on 2020-06-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200628_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceuser',
            name='is_retailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='W7mUkN8bkAUDpptf', unique=True),
        ),
    ]
