# Generated by Django 2.2.13 on 2020-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200617_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Smartphones', 'Smartphones'), ('Tablets', 'Tablets'), ('Headphones', 'Headphones'), ('Camera', 'Camera'), ('Accesories', 'Accesories'), ('Tv', 'Tv')], max_length=50),
        ),
    ]
