# Generated by Django 2.2.13 on 2020-06-17 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200617_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
