# Generated by Django 2.2.13 on 2020-06-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200630_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='8mWwA8wDaEXJvkoE', unique=True),
        ),
        migrations.DeleteModel(
            name='EcommerceUser',
        ),
    ]
