# Generated by Django 2.2.13 on 2020-06-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200609_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_retailer',
            field=models.BooleanField(default=False),
        ),
    ]
