# Generated by Django 2.2.13 on 2020-06-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200624_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='ASaULWBpqrNs4tz8', unique=True),
        ),
    ]
