# Generated by Django 2.2.13 on 2020-06-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200630_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='xSjlMb6YXh3Yi8JJ', unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
