# Generated by Django 2.2.13 on 2020-07-07 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="phone number must be entered in the format:'+2547*******'", regex='^(?:254|\\+254|0)?(7(?:[129][0-9])|(?:0[0-9]))[0-9]{6})$')]),
        ),
    ]
