# Generated by Django 2.2.13 on 2020-07-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200705_1009'),
        ('core', '0005_auto_20200707_1700'),
    ]

    operations = [
    ]
