# Generated by Django 2.2.13 on 2020-07-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200708_1556'),
        ('core', '0007_item_quantity'),
    ]

    operations = [
    ]
